name: Deploy to STAGE

on:
  push:
    branches:
      - master

concurrency: stage_environment

jobs:
  apply-terraform:
    runs-on: ubuntu-20.04

    steps:
      - name: Run terraform
        run: |
          echo "terraform apply"

  backend:
    needs: [apply-terraform]
    uses: mariuspaliga/aradelc/.github/workflows/deploy.yaml@master
    with:
      environment: stage
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
